all:
  hosts:
    dev:
      ansible_host: 192.168.0.50
      ip: 192.168.0.50
      access_ip: 192.168.0.50
  children:
    kube_control_plane:
      hosts:
        dev:
    kube_node:
      hosts:
        dev:
    etcd:
      hosts:
        dev:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
