Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.hostname = "vm1"
  config.vm.network "public_network", ip: "192.168.0.60"

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "4096"
    v.vmx["numvcpus"] = "2"
  end

  config.vm.provision "shell",
    inline: "sudo apt-get update && sudo apt-get install net-tools"

  # config.vm.define "vm1" do |vm1|

  #   vm1.vm.hostname = "vm1"
  #   vm1.vm.network "public_network", ip: "192.168.0.80"

  #   vm1.vm.provider "vmware_desktop" do |v|
  #     v.vmx["memsize"] = "4096"
  #     v.vmx["numvcpus"] = "2"
  #   end

  #   vm1.vm.provision "shell",
  #     inline: "sudo apt-get update && sudo apt-get install net-tools"
  # end

  # config.vm.define "vm2" do |vm2|

  #   vm2.vm.hostname = "vm2"
  #   vm2.vm.network "public_network", ip: "192.168.0.81"

  #   vm2.vm.provider "vmware_desktop" do |v|
  #     v.vmx["memsize"] = "4096"
  #     v.vmx["numvcpus"] = "2"
  #   end

  #   vm2.vm.provision "shell",
  #     inline: "sudo apt-get update && sudo apt-get install net-tools"
  # end
end