control-planes:
  - name: master
    box: generic/ubuntu2204
    hostname: master
    ip: 192.168.0.80
    provider: vmware_desktop
    memory: 4096
    cpu: 4
workers:
  - name: worker1
    box: generic/ubuntu2204
    hostname: worker1
    ip: 192.168.0.81
    provider: vmware_desktop
    memory: 4096
    cpu: 4