require "yaml"

conf = YAML.load_file(File.join(File.dirname(__FILE__), "config.yml"))

# native
s = "../../scripts"

# vm
h = "/home/vagrant"
hs = "#{h}/scripts"
hsm = "#{hs}/misc"
hsl = "#{hs}/lang"
hsk = "#{hs}/kubernetes"
hk = "#{h}/kubespray"

Vagrant.configure("2") do |config|
  config.vm.box = conf["box"]
  config.vm.hostname = conf["hostname"]
  config.vm.network "public_network", ip: conf["ip"]

  config.vm.provider conf["provider"] do |v|
    v.vmx["memsize"] = conf["memory"]
    v.vmx["numvcpus"] = conf["cpu"]
  end

  config.vm.synced_folder "#{s}", "#{h}/scripts"

  config.vm.provision "shell", inline: "#{hsm}/base-settings.sh", privileged: false
  config.vm.provision "shell", inline: "#{hs}/zsh/init.sh", privileged: false
  config.vm.provision "shell", inline: "#{hsm}/modern-linux.sh #{h}", privileged: false
  config.vm.provision "shell", inline: "#{hsm}/tools.sh", privileged: false
  config.vm.provision "shell", inline: "#{hsm}/docker.sh", privileged: false

  # config.vm.provision "shell", inline: "#{hsl}/go.sh", privileged: false
  # config.vm.provision "shell", inline: "#{hsl}/java.sh", privileged: false
  # config.vm.provision "shell", inline: "#{hsl}/nodejs.sh", privileged: false
  # config.vm.provision "shell", inline: "#{hsl}/python.sh", privileged: false

  config.vm.provision "file", source: "./kubespray", destination: "#{hk}"
  config.vm.provision "shell", inline: "chmod -R 777 #{hk}", privileged: false
  config.vm.provision "shell", inline: "cp -rfp #{hsk}/kubespray/bootstrap/* #{hk}", privileged: false
  config.vm.provision "shell", inline: "#{hsk}/kubespray/nodes/node-base.sh", privileged: false
  config.vm.provision "shell", inline: "#{hsk}/misc/aliases.sh", privileged: false
  config.vm.provision "shell", inline: "#{hk}/install.sh", privileged: false
end
