all:
  hosts:
    master:
      ansible_host: 192.168.0.80
      ip: 192.168.0.80
      access_ip: 192.168.0.80
    worker1:
      ansible_host: 192.168.0.81
      ip: 192.168.0.81
      access_ip: 192.168.0.81
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        worker1:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
