require "yaml"

conf = YAML.load_file(File.join(File.dirname(__FILE__), "config.yml"))

# native
s = "../../scripts"

# vm
h = "/home/vagrant"
hs = "#{h}/scripts"
hsm = "#{hs}/misc"
hsk = "#{hs}/kubernetes"
hk = "#{h}/kubespray"

Vagrant.configure("2") do |config|

  conf["control-planes"].each do |cp|
    config.vm.define cp["name"] do |cfg|
      cfg.vm.box = cp["box"]
      cfg.vm.network "public_network", ip: cp["ip"]
      cfg.vm.hostname = cp["hostname"]
      
      cfg.vm.provider cp["provider"] do |v|
        v.vmx["memsize"] = cp["memory"]
        v.vmx["numvcpus"] = cp["cpu"]
      end

      cfg.vm.synced_folder "#{s}", "#{hs}"

      cfg.vm.provision "shell", inline: "#{hsm}/base-preshell.sh", privileged: false

      cfg.vm.provision "file", source: "./kubespray", destination: "#{hk}"
      cfg.vm.provision "shell", inline: "cp -rfp #{hsk}/kubespray/bootstrap/* #{hk}", privileged: false
      cfg.vm.provision "shell", inline: "#{hsk}/kubespray/nodes/node-base.sh", privileged: false
      cfg.vm.provision "shell", inline: "#{hsk}/misc/aliases.sh", privileged: false
      cfg.vm.provision "shell", inline: "#{hk}/install.sh", privileged: false
    end
  end

  conf["workers"].each do |wk|
    config.vm.define wk["name"] do |cfg|
      cfg.vm.box = wk["box"]
      cfg.vm.network "public_network", ip: wk["ip"]
      cfg.vm.hostname = wk["hostname"]
      
      cfg.vm.provider wk["provider"] do |v|
        v.vmx["memsize"] = wk["memory"]
        v.vmx["numvcpus"] = wk["cpu"]
      end

      cfg.vm.synced_folder "#{s}", "#{hs}"

      cfg.vm.provision "shell", inline: "#{hsm}/base-preshell.sh", privileged: false

      cfg.vm.provision "shell", inline: "#{hsk}/kubespray/nodes/node-base.sh", privileged: false
    end
  end
end
