require "yaml"

conf = YAML.load_file(File.join(File.dirname(__FILE__), "config.yml"))

# native
s = "../../scripts"

# vm
h = "/home/vagrant"
hs = "#{h}/scripts"

Vagrant.configure("2") do |config|
  config.vm.box = conf["box"]
  config.vm.hostname = conf["hostname"]
  config.vm.network "public_network", ip: conf["ip"]

  config.vm.provider conf["provider"] do |v|
    v.vmx["memsize"] = conf["memory"]
    v.vmx["numvcpus"] = conf["cpu"]
  end

  config.vm.synced_folder "#{s}", "#{hs}"
  config.vm.provision "shell", inline: "sudo #{hs}/zsh/init-remote.sh vagrant"
  config.vm.provision "shell", inline: "sudo #{hs}/misc/modern-linux.sh #{h}"
  config.vm.provision "shell", inline: "sudo #{hs}/misc/tools.sh"
end
